project_name: tb

before:
  hooks:
    - go mod tidy
    - make artifacts

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - README.md
      - artifacts/tb.bash
      - artifacts/_tb

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - tap:
      owner: TouchBistro
      name: homebrew-tap
    commit_author:
      name: touchbistro-github
      email: devops@touchbistro.com
    folder: Formula
    description: "a CLI for running services on a development machine"

    test: |
      system "#{bin}/tb --version"

    install: |
      bin.install "tb"
      bash_completion.install "artifacts/tb.bash"
      zsh_completion.install "artifacts/_tb"

release:
  github:
    owner: TouchBistro
    name: tb
  name_template: "{{.ProjectName}}-v{{.Version}}"
