project_name: tb

before:
  hooks:
    - go mod tidy
    - go run scripts/build-artifacts/main.go

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/TouchBistro/tb/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - artifacts/tb.bash
      - artifacts/_tb
      - artifacts/man1/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - tap:
      owner: TouchBistro
      name: homebrew-tap
    commit_author:
      name: touchbistro-github
      email: devops@touchbistro.com
    folder: Formula
    description: "a CLI for running services on a development machine"

    test: |
      system "#{bin}/tb --version"

    install: |
      bin.install "tb"
      bash_completion.install "artifacts/tb.bash"
      zsh_completion.install "artifacts/_tb"
      man1.install Dir["dist/man1/*.1"]

release:
  github:
    owner: TouchBistro
    name: tb
  name_template: "{{.ProjectName}}-v{{.Version}}"
