version: '3.7'

x-json-logger-config:
  &json-logger-config
  LOGGER_CONFIG_JSON: >
    {
      "transports": {
        "devConsole": {
          "provider": "winston.transports.Console",
          "config": {
            "colorize": true,
            "timestamp": true,
            "json": false
          }
        }
      },
      "env": {
        "development": {
          "rules": [
            {
              "pattern": "*",
              "binding": {
                "transport": ["devConsole"],
                "level": "info"
              }
            }
          ]
        }
      }
    }

x-postgresconnect:
  &postgres-connect
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: core
  DB_PASSWORD: localdev
  DB_DISABLE_SSL: "true"

x-nodeservice:
  &node-service
  << : *json-logger-config
  HTTP_PORT: 8080

x-partners-etl-service-boilerplate:
  &partners-etl-service-boilerplate
  env_file:
    - ./partners-etl-service/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *node-service
    << : *postgres-connect
    AWS_S3_ENDPOINT: http://localstack:4572
    AWS_S3_STUB: "false"
    PARTNER_CONFIG_SERVICE_URL: http://partners-config-service-ecr:8080
    TASK_PROVIDER: awssqs
    TASK_AWS_SQS_CONFIG_JSON: >
      {
        "etl.job.execute": {
          "queueURL": "http://localstack:4576/queue/etlExecute",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        }
      }
    TOUCHBISTRO_LEGACY_CLOUD_BASE_URL: http://cloud-server-ecr:3000/api/v2_5
  ports:
    - "8888:8080"
  depends_on:
    - postgres
    - localstack

x-partners-config-service-boilerplate:
  &partners-config-service-boilerplate
  env_file:
    - ./partners-config-service/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    TASK_PROVIDER: awssqs
    TASK_AWS_SQS_CONFIG_JSON: >
      {
        "partners-config.task.venueIntegrationUpdate": {
          "queueURL": "http://localstack:4576/queue/venueIntegrationUpdate",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        }
      }
  ports:
    - "8090:8080"
  depends_on:
    - postgres
    - localstack

x-partners-orchestration-service-boilerplate:
  &partners-orchestration-service-boilerplate
  env_file:
    - ./partners-orchestration-service/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    LEGACY_CLOUD_SERVICE_URL: http://touchbistro-node-legacy-cloud-ecr:8080
    PARTNER_CONFIG_SERVICE_URL: http://partners-config-service-ecr:8080
    TASK_PROVIDER: awssqs
    TASK_AWS_SQS_CONFIG_JSON: >
      {
        "workflow.runNextInstruction": {
          "queueURL": "http://localstack:4576/queue/workflowRunNextInstruction",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "partners-config.task.venueIntegrationUpdate": {
          "queueURL": "http://localstack:4576/queue/venueIntegrationUpdate",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        }
      }
  ports:
    - "8085:8080"
  depends_on:
    - postgres
    - localstack

services:
  partners-etl-service-ecr:
    << : *partners-etl-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/partners-etl-service:master
    container_name: partners-devtools_partners-etl-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  partners-etl-service:
    << : *partners-etl-service-boilerplate
    build:
      target: dev
      context: ./partners-etl-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: partners-devtools_partners-etl-service
    container_name: partners-devtools_partners-etl-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./partners-etl-service:/home/node/app:delegated
      - partners-etl-service-node_modules:/home/node/app/node_modules

  partners-config-service-ecr:
    << : *partners-config-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/partners-config-service:master
    container_name: partners-devtools_partners-config-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  partners-config-service:
    << : *partners-config-service-boilerplate
    build:
      target: dev
      context: ./partners-config-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: partners-devtools_partners-config-service
    container_name: partners-devtools_partners-config-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./partners-config-service:/home/node/app:delegated
      - partners-config-service-node_modules:/home/node/app/node_modules

  partners-orchestration-service-ecr:
    << : *partners-orchestration-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/partners-orchestration-service:master
    container_name: partners-devtools_partners-orchestration-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  partners-orchestration-service:
    << : *partners-orchestration-service-boilerplate
    build:
      target: dev
      context: ./partners-orchestration-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: partners-devtools_partners-orchestration-service
    container_name: partners-devtools_partners-orchestration-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./partners-orchestration-service:/home/node/app:delegated
      - partners-orchestration-service-node_modules:/home/node/app/node_modules

volumes:
  partners-etl-service-node_modules:
  partners-config-service-node_modules:
  partners-orchestration-service-node_modules:
