version: '3.7'

x-venue-admin-frontend:
  &venue-admin-frontend
  env_file:
    - ./venue-admin-frontend/.env.example
  environment:
    - CORE_BACKEND_URL_BASE=http://core-backend-ecr:8080
    - TOUCHBISTRO_PARTNER_CONFIG_URL_BASE=http://touchbistro-partner-config-ecr:8080
    - TOUCHBISTRO_LEGACY_BRIDGE_API_URL_BASE=http://touchbistro-node-legacy-cloud-ecr:8080
    - HTTP_PORT=9002   # VAF will default to :5000 for local server development.
    - NODE_ENV=production
  ports:
    - "9002:9002"
  # Note the `../`, since the Dockerfile executes from $HOME/app/dist 
  entrypoint: [ "bash", "../docker-entrypoint.sh" ]  
  command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'
  depends_on:
    - core-backend-ecr
    - cloud-server-ecr    
    - touchbistro-node-legacy-cloud-ecr
    - touchbistro-partner-config-ecr

services:
  venue-admin-frontend:
    << : *venue-admin-frontend
    build:
      target: release
      context: ./venue-admin-frontend
      args:
        - NPM_TOKEN=$NPM_TOKEN
        # ** DO NOT SET THIS IN CI OR PRODUCTION-LIKE ENVIRONMENTS. **
        # ^ This is to reduce the hard dependency on cloud-server[-frontend]
        # until "mokta" is available.
        # - SSO_INSECURE_BACKDOOR_DO_NOT_USE_ANYWHERE_BUT_LOCALHOST==insecure
    container_name: venue-admin-frontend
    # depends_on:
    #   - core-backend-ecr
    #   - 

  venue-admin-frontend-ecr:
    << : *venue-admin-frontend
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/admin-service:${VAF_TAG:-master}
    container_name: venue-admin-frontend-ecr${VAF_TAG:-master}
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

