version: '3.7'

x-json-logger-config:
  &json-logger-config
  LOGGER_CONFIG_JSON: >
    {
      "transports": {
        "devConsole": {
          "provider": "winston.transports.Console",
          "config": {
            "colorize": true,
            "timestamp": true,
            "json": false
          }
        }
      },
      "env": {
        "development": {
          "rules": [
            {
              "pattern": "*",
              "binding": {
                "transport": ["devConsole"],
                "level": "info"
              }
            }
          ]
        }
      }
    }

x-postgresconnect:
  &postgres-connect
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: core
  DB_PASSWORD: localdev
  DB_DISABLE_SSL: "true"

x-mokta-boilerplate:
  &mokta-boilerplate
  env_file:
    - ./mokta/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *json-logger-config
    << : *postgres-connect
    HTTP_PORT: 8080
  ports:
    - "9443:8080"
  depends_on:
    - postgres

x-identity-user-service-boilerplate:
  &identity-user-service-boilerplate
  env_file:
    - ./identity-user-service/.env.example
  ports:
    - "8777:8080"

services:
  mokta:
    << : *mokta-boilerplate
    build:
      target: dev
      context: ./mokta
      args:
        - NPM_TOKEN=$NPM_TOKEN
    container_name: mokta_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'

  mokta-ecr:
    << : *mokta-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/mokta:develop
    container_name: mokta-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  identity-user-service:
    << : *identity-user-service-boilerplate
    build:
      target: dev
      context: ./identity-user-service
      args:
        - NPM_TOKEN=$NPM_TOKEN
    container_name: identity-user-service_container
    environment:
      << : *json-logger-config
      HTTP_PORT: 8080
      OKTA_BASE_URL: https://mokta:8080
      INSECURE_DISABLE_SSL_VALIDATION: 'true'

  identity-user-service-ecr:
    << : *identity-user-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/touchbistro-identity-user:develop
    container_name: identity-user-service-ecr_container
    environment:
      << : *json-logger-config
      HTTP_PORT: 8080
      OKTA_BASE_URL: https://mokta-ecr:8080
      INSECURE_DISABLE_SSL_VALIDATION: 'true'
