version: '3.7'

x-json-logger-config:
  &json-logger-config
  LOGGER_CONFIG_JSON: >
    {
      "transports": {
        "devConsole": {
          "provider": "winston.transports.Console",
          "config": {
            "colorize": true,
            "timestamp": true,
            "json": false
          }
        }
      },
      "env": {
        "development": {
          "rules": [
            {
              "pattern": "*",
              "binding": {
                "transport": ["devConsole"],
                "level": "info"
              }
            }
          ]
        }
      }
    }

x-provisioning-service-boilerplate:
  &provisioning-service-boilerplate
  env_file:
    - ./provisioning-service/.env.compose
  environment:
    HTTP_PORT: 8080
    << : *json-logger-config
  #entrypoint: ["bash", "./docker-entrypoint.sh"]
  ports:
    - "8666:8080"
  depends_on:
    - postgres

x-health-clinic-boilerplate:
  &health-clinic-boilerplate
  command: ["tail", "-f", "/dev/null"]
  env_file:
    - ./health-clinic/.env.compose
  ports:
    - "8089:8089"

x-core-backend-boilerplate:
  &core-backend-boilerplate
  command: ["tail", "-f", "/dev/null"]
  entrypoint: ["bash", "./entrypoints/server-entrypoint.sh"]
  env_file:
    - ./core-backend/.env.example
  environment:
    HTTP_PORT: 8080
    DB_HOST: postgres
    PROVISIONING_JWKS_URI: http://provisioning-service-ecr:8080/external/jwks
    AWS_S3_CORE_IMAGE_URL_TEMPLATE: http://localstack:4572/%%s3Bucket%%/%%s3ObjectKey%%
    AWS_S3_CORE_FILE_URL_TEMPLATE: http://localstack:4572/%%s3Bucket%%/%%s3ObjectKey%%
    AWS_S3_ENDPOINT: http://localstack:4572
    LOCALSTACK_SQS_URL: http://localstack:4576
    USE_INSECURE_IMPERSONATE: insecure
    TASK_AWS_SQS_CONFIG_JSON: >
      {"core.task.data.migration":{"queueURL":"http://localstack:4576/queue/coreTest","messageThrottle":1,"visibilityTimeout":10,"waitTimeSeconds":5,"sleepTimeSeconds":5}}
    << : *json-logger-config
  ports:
    - "8081:8080"  # Main HTTP port
    - "9901:9229"  # 9229, 9330: Node debugger
    - "9902:9230"  
    - "4001:4001"  # JSDoc server
    # - "8089:8089"   # Not used?
  depends_on:
    - localstack
    - postgres

services:
  core-backend-ecr:
    << : *core-backend-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/core-backend:master
    command: >
      bash -c '
        echo '...done'
        if [ "$START_SERVER" = "true" ]; then
          echo "Starting server.."
          yarn serve
        else
          echo "Not starting server.."
          tail -f /dev/null
        fi'
    container_name: core-backend-ecr

  core-backend:
    << : *core-backend-boilerplate
    build:
      target: local
      context: ./core-backend
      args:
        - NPM_TOKEN=$NPM_TOKEN
        - GITSHA=TESTME
    image: core-devtools_core-backend
    container_name: core-devtools_core-backend_container
    command: >
      bash -c '
        echo '...done'
        if [ "$START_SERVER" = "true" ]; then
          echo "Starting server.."
          yarn start
        else
          echo "Not starting server.."
          tail -f /dev/null
        fi'
    volumes:
      - ./core-backend:/home/node/app:delegated
      - core-backend-node_modules:/home/node/app/node_modules:delegated

  provisioning-service-ecr:
    << : *provisioning-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/touchbistro-provisioning-service:develop
    container_name: provisioning-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  provisioning-service:
    << : *provisioning-service-boilerplate
    build:
      context: ./provisioning-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: core-devtools_provisioning-service
    container_name: core-devtools_provisioning-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'

  health-clinic-ecr:
    << : *health-clinic-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/touchbistro-health-clinic:master
    container_name: core-devtools_health-clinic-ecr_container

  health-clinic:
    << : *health-clinic-boilerplate
    build:
      context: ./health-clinic
    image: core-devtools_health-clinic
    container_name: core-devtools_health-clinic_container
    volumes:
      - ./health-clinic:/home/python/app

volumes:
  core-backend-node_modules:
