version: '3.7'

x-json-logger-config:
  &json-logger-config
  LOGGER_CONFIG_JSON: >
    {
      "transports": {
        "devConsole": {
          "provider": "winston.transports.Console",
          "config": {
            "colorize": true,
            "timestamp": true,
            "json": false
          }
        }
      },
      "env": {
        "development": {
          "rules": [
            {
              "pattern": "*",
              "binding": {
                "transport": ["devConsole"],
                "level": "info"
              }
            }
          ]
        }
      }
    }

x-postgresconnect:
  &postgres-connect
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: core
  DB_PASSWORD: localdev
  DB_DISABLE_SSL: "true"

x-nodeservice:
  &node-service
  << : *json-logger-config
  HTTP_PORT: 8080

x-ordering-ooa-service-boilerplate:
  &ordering-ooa-service-boilerplate
  env_file:
    - ./ordering-ooa-service/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    TASK_PROVIDER: awssqs
    TASK_AWS_SQS_CONFIG_JSON: >
      {
        "ordering.notification.venue.menuUpdate": {
          "queueURL": "http://localstack:4576/queue/menuUpdate",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "ordering.notification.venue.orderCancelled": {
          "queueURL": "http://localstack:4576/queue/orderCancelled",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "ordering.notification.venue.ordersPending": {
          "queueURL": "http://localstack:4576/queue/ordersPending",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "ordering.notification.gateway.ordersStatus": {
          "queueURL": "http://localstack:4576/queue/ordersStatus",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "ordering.order.expiryCheck": {
          "queueURL": "http://localstack:4576/queue/expiryCheck",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        },
        "ordering.order.validate": {
          "queueURL": "http://localstack:4576/queue/orderValidate",
          "messageThrottle": 1,
          "visibilityTimeout": 10,
          "waitTimeSeconds": 5,
          "sleepTimeSeconds": 5
        }
      }
    TOUCHBISTRO_LEGACY_CLOUD_BASE_URL: http://legacy-bridge-cloud-service-ecr:8080
  ports:
    - "8005:8080"
  depends_on:
    - postgres
    - localstack

x-ordering-demo-frontend-boilerplate:
  &ordering-demo-frontend-boilerplate
  env_file:
    - ./ordering-demo-frontend/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    DELIVEROO_BASE_URL: http://ordering-deliveroo-service-ecr:8080
    DELIVEROO_DISABLED: 'false'
    ORDERING_BASE_URL: http://ordering-ooa-service-ecr:8080/external
    URL_CALLBACK_URL: http://ordering-demo-frontend-ecr:8080/callback
  ports:
    - "8010:8080"
  depends_on:
    - postgres

x-ordering-demo-frontend-venue-boilerplate:
  &ordering-demo-frontend-venue-boilerplate
  env_file:
    - ./ordering-demo-frontend/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    INVENUE_BASE_URL: http://ordering-ooa-service-ecr:8080/external
    MODE: venue
  ports:
    - "8020:8080"
  depends_on:
    - postgres

x-ordering-gateways-frontend-boilerplate:
  &ordering-gateways-frontend-boilerplate
  env_file:
    - ./ordering-gateways-frontend/.env.example
  environment:
    << : *node-service
    ORDERING_BASE_URL: http://ordering-ooa-service-ecr:8080/external
    ORDERING_INTERNAL_BASE_URL: http://ordering-ooa-service-ecr:8080/internal 
  ports:
    - "8030:8080"

x-ordering-deliveroo-service-boilerplate:
  &ordering-deliveroo-service-boilerplate
  env_file:
    - ./ordering-deliveroo-service/.env.example
  entrypoint: ["bash", "./docker-entrypoint.sh"]
  environment:
    << : *postgres-connect
    << : *node-service
    DELIVEROO_BASE_URL: http://ordering-demo-frontend-ecr:8080/deliveroo
    ORDERING_BASE_URL: http://ordering-ooa-service-ecr:8080/external
    URL_BASE_URL: http://ordering-deliveroo-service-ecr:8080
  ports:
    - "8015:8080"
  depends_on:
    - postgres

services:
  ordering-ooa-service-ecr:
    << : *ordering-ooa-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/ordering-ooa-service:develop
    container_name: ordering-devtools_ordering-ooa-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  ordering-ooa-service:
    << : *ordering-ooa-service-boilerplate
    build:
      target: dev
      context: ./ordering-ooa-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: ordering-devtools_ordering-ooa-service
    container_name: ordering-devtools_ordering-ooa-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./ordering-ooa-service:/home/node/app:delegated
      - ordering-ooa-service-node_modules:/home/node/app/node_modules

  ordering-demo-frontend-ecr:
    << : *ordering-demo-frontend-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/touchbistro-ordering-gateway:develop
    container_name: ordering-devtools_ordering-demo-frontend-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  ordering-demo-frontend:
    << : *ordering-demo-frontend-boilerplate
    build:
      target: dev
      context: ./ordering-demo-frontend
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: ordering-devtools_ordering-demo-frontend
    container_name: ordering-devtools_ordering-demo-frontend_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./ordering-demo-frontend:/home/node/app:delegated
      - ordering-demo-frontend-node_modules:/home/node/app/node_modules

  ordering-demo-frontend-venue:
    build:
      target: dev
      context: ./ordering-demo-frontend
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: ordering-devtools_ordering-demo-frontend-venue
    container_name: ordering-devtools_ordering-demo-frontend-venue_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    env_file:
      - ./ordering-demo-frontend/.env.example
    environment:
      << : *postgres-connect
      << : *node-service
      INVENUE_BASE_URL: http://ordering-ooa-service-ecr:8080/external
      MODE: venue
    volumes:
      - ./ordering-demo-frontend:/home/node/app:delegated
      - ordering-demo-frontend-venue-node_modules:/home/node/app/node_modules
    ports:
      - "8020:8080"
    depends_on:
      - postgres

  ordering-gateways-frontend-ecr:
    << : *ordering-gateways-frontend-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/ordering-gateways-frontend:develop
    container_name: ordering-devtools_ordering-gateways-frontend-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  ordering-gateways-frontend:
    << : *ordering-gateways-frontend-boilerplate
    build:
      target: dev
      context: ./ordering-gateways-frontend
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: ordering-devtools_ordering-gateways-frontend
    container_name: ordering-devtools_ordering-gateways-frontend_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./ordering-gateways-frontend:/home/node/app:delegated
      - ordering-gateways-frontend-node_modules:/home/node/app/node_modules

  ordering-deliveroo-service-ecr:
    << : *ordering-deliveroo-service-boilerplate
    image: 651264383976.dkr.ecr.us-east-1.amazonaws.com/deliveroo-service:master
    container_name: ordering-devtools_ordering-deliveroo-service-ecr_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn serve; else tail -f /dev/null; fi'

  ordering-deliveroo-service:
    << : *ordering-deliveroo-service-boilerplate
    build:
      target: dev
      context: ./ordering-deliveroo-service
      args:
        - NODE_ENV=development
        - NPM_TOKEN=$NPM_TOKEN
    image: ordering-devtools_ordering-deliveroo-service
    container_name: ordering-devtools_ordering-deliveroo-service_container
    command: bash -c 'if [ "$START_SERVER" = "true" ]; then yarn start; else tail -f /dev/null; fi'
    volumes:
      - ./ordering-deliveroo-service:/home/node/app:delegated
      - ordering-deliveroo-service-node_modules:/home/node/app/node_modules

volumes:
  ordering-ooa-service-node_modules:
  ordering-demo-frontend-node_modules:
  ordering-demo-frontend-venue-node_modules:
  ordering-deliveroo-service-node_modules:
  ordering-gateways-frontend-node_modules:
