version: '3.7'

services:
  postgres:
    image: postgres:10.6-alpine
    container_name: core-devtools_postgres_container
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=localdev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: cloud-server-redis_container
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: core-devtools_localstack_container
    ports:
      - "9888:8080" # web interface
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=s3,sqs
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-entrypoint.sh:/docker-entrypoint-initaws.d/aa_localstack_entrypoint.sh" # docker-entrypoint-initaws.d files are run in alphabetical order
      - "./core-backend/entrypoints/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/zz_localstack_core_backend.sh"
      - "./touchbistro-ordering-service/entrypoints/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/zz_localstack_ordering_service.sh"
      - "./touchbistro-etl/entrypoints/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/zz_localstack_etl.sh"
      - "./touchbistro-partner-config/entrypoints/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/zz_localstack_partner_config.sh"
      - "./touchbistro-orchestration-partner/entrypoints/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/zz_localstack_orchestration_partner.sh"
    logging:
      driver: none   # Remove this line to see noisy localstack logs.

volumes:
  postgres:
