---
playlists:
  auth:
    - postgres
    - mokta
    - identity-user-service
  cloud:
    - redis
    - legacy-database
    - cloud-server
    - cloud-server-frontend
    - dotnet-manage
    - dotnet-api
    - legacy-bridge-manage-service
  core:
    - core-backend
    - postgres
    - localstack
    - provisioning-service
  ordering:
    - postgres
    - localstack
    - ordering-ooa-service
    - ordering-gateways-frontend
    - ordering-deliveroo-service
    - ordering-demo-frontend
    - ordering-demo-frontend-venue
  partners:
    - postgres
    - partners-etl-service
    - partners-config-service
    - partners-orchestration-service
    - legacy-bridge-cloud-service
    - localstack
    - legacy-database
  venueadmin:
    - localstack
    - postgres
    - core-backend
    - legacy-database
    - redis
    - cloud-server
    - cloud-server-frontend
    - legacy-bridge-cloud-service
    - partners-config-service
    - venue-admin-frontend
  venueadmin-depsonly:
    - localstack
    - postgres
    - core-backend
    - legacy-database
    - redis
    - cloud-server
    - cloud-server-frontend
    - legacy-bridge-cloud-service
    - partners-config-service
