---
playlists:
  auth:
    - postgres
    - mokta
    - touchbistro-user-profile-service
  cloud:
    - redis
    - touchbistro-manage-database
    - cloud-server
    - cloud-server-frontend
    - dotnet-manage
    - dotnet-api
    - legacy-bridge-manage
  core:
    - core-backend
    - postgres
    - localstack
    - provisioning-service
  ordering:
    - postgres
    - localstack
    - touchbistro-ordering-service
    - touchbistro-ordering-frontend
    - ordering-deliveroo
    - ordering-demo-frontend
    - ordering-demo-frontend-venue
  partners:
    - postgres
    - touchbistro-etl
    - touchbistro-partner-config
    - touchbistro-orchestration-partner
    - touchbistro-node-legacy-cloud
    - localstack
    - touchbistro-manage-database
  venueadmin:
    - localstack
    - postgres
    - core-backend
    - touchbistro-manage-database
    - redis
    - cloud-server
    - cloud-server-frontend
    - touchbistro-node-legacy-cloud
    - touchbistro-partner-config
    - venue-admin-frontend
  venueadmin-depsonly:
    - localstack
    - postgres
    - core-backend
    - touchbistro-manage-database
    - redis
    - cloud-server
    - cloud-server-frontend
    - touchbistro-node-legacy-cloud
    - touchbistro-partner-config
