version: 2.1

cache_key: &cache_key tb-deps-20200924-{{ checksum "go.sum" }}

jobs:
  lint-build-test:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          keys:
            - *cache_key
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          name: Cache dependencies
          key: *cache_key
          paths:
            - ~/go/pkg
            - bin/golangci-lint
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Build tb
          command: make build
      - run:
          name: Run tests
          command: make test-ci
      - run:
          name: Verify tb runs
          command: ./tb --help

workflows:
  lint-build-test:
    jobs:
      - lint-build-test
