backoffice-customer-service:
  repo: backoffice-customer-service
  migrations: true
  ecr: true
  ecrTag: master
cloud-server:
  repo: cloud-server
  migrations: false
  ecr: true
  ecrTag: develop
cloud-server-frontend:
  repo: cloud-server-frontend
  migrations: false
  ecr: true
  ecrTag: develop
dotnet-api:
  repo: dotnet-depot
  migrations: false
  ecr: false
dotnet-manage:
  repo: dotnet-depot
  migrations: false
  ecr: false
health-clinic:
  repo: health-clinic
  migrations: false
  ecr: true
  ecrTag: master
identity-user-service:
  repo: identity-user-service
  migrations: false
  ecr: true
  ecrTag: master
infrastructure-auth-service:
  repo: infrastructure-auth-service
  migrations: true
  ecr: true
  ecrTag: master
legacy-bridge-cloud-service:
  repo: legacy-bridge-cloud-service
  migrations: false
  ecr: true
  ecrTag: master
legacy-bridge-manage-service:
  repo: legacy-bridge-manage-service
  migrations: false
  ecr: true
  ecrTag: develop
legacy-database:
  repo: legacy-database
  migrations: true
  ecr: true
  ecrTag: master-db-migrate-with-seeds
localstack:
  migrations: false
  ecr: false
  dockerhubImage: localstack/localstack
loyalty-gateway-service:
  repo: loyalty-gateway-service
  migrations: true
  ecr: true
  ecrTag: master
postgres:
  migrations: false
  ecr: false
  dockerhubImage: postgres:10.6-alpine
redis:
  migrations: false
  ecr: false
  dockerhubImage: redis:4-alpine
mokta:
  repo: mokta
  migrations: true
  ecr: true
  ecrTag: master
ordering-deliveroo-service:
  repo: ordering-deliveroo-service
  migrations: true
  ecr: true
  ecrTag: master
ordering-demo-frontend:
  repo: ordering-demo-frontend
  migrations: true
  ecr: true
  ecrTag: master
ordering-demo-frontend-venue:
  repo: ordering-demo-frontend
  migrations: false
  ecr: false
ordering-engine-service:
  repo: ordering-engine-service
  migrations: false
  ecr: true
  ecrTag: master
ordering-online-frontend:
  repo: ordering-online-frontend
  migrations: false
  ecr: true
  ecrTag: master
ordering-gateways-frontend:
  repo: ordering-gateways-frontend
  migrations: false
  ecr: true
  ecrTag: master
ordering-ooa-service:
  repo: ordering-ooa-service
  migrations: true
  ecr: true
  ecrTag: master
partners-config-service:
  repo: partners-config-service
  migrations: true
  ecr: true
  ecrTag: master
partners-etl-service:
  repo: partners-etl-service
  migrations: true
  ecr: true
  ecrTag: master
partners-orchestration-service:
  repo: partners-orchestration-service
  migrations: true
  ecr: true
  ecrTag: master
partners-reservations-service:
  repo: partners-reservations-service
  migrations: true
  ecr: true
  ecrTag: master
payments-gateway-service:
  repo: payments-gateway-service
  migrations: true
  ecr: true
  ecrTag: master  
singleapp-database:
  repo: singleapp-database
  migrations: false
  ecr: true
  ecrTag: master
venue-admin-frontend:
  repo: venue-admin-frontend
  migrations: false
  ecr: true
  ecrTag: master
venue-core-service:
  repo: venue-core-service
  migrations: true
  ecr: true
  ecrTag: master
venue-provisioning-service:
  repo: venue-provisioning-service
  migrations: true
  ecr: true
  ecrTag: master
venue-upload-service:
  repo: venue-upload-service
  migrations: false
  ecr: true
  ecrTag: master
legacy-upload-service:
  repo: legacy-upload-service
  migrations: false
  ecr: true
  ecrTag: master